### ISSUE TITLE
player model check bypass

### ISSUE THREAD

**Issue by primemb** [kepmehz/rdr2-doc#2]
hi thank you so much for the very nice info 👍 👍
I want to ask if you know how game check and validate the player model because right now is SP mode if you change player model it back to normal asap and in MP you get a kick from the server,

I checked the game script but find nothings I just find this on scripts : 

```
void func_230(int iParam0, int iParam1)
{
	struct<30> Var0;
	struct<9> Var30;
	int iVar39;

	if (iParam1 == 3)
	{
		return;
	}
	if (iParam0 == 3 && iParam1 == 2)
	{
		if (func_519(255))
		{
			DEBUG::_0xA308F935BDECCEC0(8, 208, "VALIDATE_PLAYER_MODEL - NET_PLAYER_STATUS_IS_USING_CUSTOM_SPAWN_CONFIG() = TRUE - using custom spawn config for respawn");
			Var30.f_6 = { ENTITY::GET_ENTITY_COORDS(PLAYER::GET_PLAYER_PED(PLAYER::PLAYER_ID()), false, false) };
			func_520(Var30.f_6, &Var0);
			if (!func_521(Var0, Var30, 1, 1, 1))
			{
				func_522(Var30.f_6, 0f, 0f, 0f, 0f, 0);
				DEBUG::_0xA308F935BDECCEC0(8, 208, "VALIDATE_PLAYER_MODEL - NET_PLAYER_STATUS_FULFILL_CUSTOM_SPAWN_CONFIG() = FALSE - using absolute coords");
			}
		}
		else
		{
			DEBUG::_0xA308F935BDECCEC0(8, 208, "VALIDATE_PLAYER_MODEL - NET_PLAYER_STATUS_IS_USING_CUSTOM_SPAWN_CONFIG() = FALSE - doing force respawn");
			func_523(1, 1);
		}
		func_234(33554432);
		func_229(8388608);
		DEBUG::_0x83407B92D46F25C3(8, 208, "[VALIDATE_PLAYER_MODEL] Could not validate player model change for more than 10 seconds | Reseting player model!");
		return;
	}
	iVar39 = iParam0 * 1000;
	switch (func_524(0))
	{
		case joaat("MPC_PLAYER_TYPE_MP_MALE"):
			iVar39 += 100;
			break;
		case joaat("MPC_PLAYER_TYPE_MP_FEMALE"):
			iVar39 += 200;
			break;
		default:
			iVar39 += 300;
			break;
	}
	func_525(52, iVar39);
}
```

**Comment by kepmehz** [comment]
Thanks for creating an issue. Model changing in SP should work properly and not reset your model I can give you an example on how to use it:
```cpp
rage::joaat_t modelHash = joaat("THE_MODEL_YOU_WANT_TO_CHANGE_TO");
				if (STREAMING::IS_MODEL_VALID(modelHash) && STREAMING::IS_MODEL_A_PED(modelHash))
				{
					if (Helpers::RageRequest(modelHash, 3000))
					{
						PLAYER::SET_PLAYER_MODEL(PLAYER::PLAYER_ID(), modelHash, true);
						PED::SET_PED_RANDOM_COMPONENT_VARIATION(PLAYER::PLAYER_PED_ID(), 1);
						STREAMING::SET_MODEL_AS_NO_LONGER_NEEDED(modelHash);
					}
				}
```
RageRequest is just:
```cpp
bool Helpers::RageRequest(uint32_t hash, uint64_t timeOut)
{
	if (!STREAMING::IS_MODEL_VALID(hash)) return false;
	if (STREAMING::HAS_MODEL_LOADED(hash)) return true;
	else
	{
		STREAMING::REQUEST_MODEL(hash, 0);

		for (timeOut += GetTickCount64(); GetTickCount64() < timeOut;)
		{
			if (STREAMING::HAS_MODEL_LOADED(hash))
				return true;
			scriptWait(0);
		}
		return false;
	}
}
```
This code works perfectly fine in Singleplayer.
But you are right changing your Player Model online will result in a Network Error. I won't give any detailed information on how their check works but the only thing I am going to say is to check the Scripts that are called every tick (update Scripts).

**Comment by primemb** [comment]
thank you so much I find out I used an online model (nude female :D) in SP that was why the model change back to the normal one I used another and it solve thank you <3

**Comment by elchoky** [comment]
Sorry for comment here, but any idea how we can protect us from crash?
Invalid models in rage, or some Rage functions like on gtav that for some reaso go overload with invalid data and send a crash to a user.
We are checkin the bypass for this model, current workin with @primerb but since you work is more deep into the engine any idea, for protections (no network events).

**Comment by kepmehz** [comment]
Since you mentioned "models." Yeah, there are ways to protect against invalid model data. Take a look at the virtual functions of CNetworkObjectMgr, which are used to create, sync, and remove models between players in the session.
